con = url("https://www.dropbox.com/scl/fo/zlkc7mwmsj2h2q53j5vn5/AK-Dhwjrlzczagsdlkkc3lo?rlkey=qx0caf1eofynrpunhlrjvgfwa&e=1&st=yc6pbrmj&dl=1")
htmlCode = readLines(con)
close.connection(con)
install.packages("httr")
install.packages("xml2")
library(httr)
library(xml2)
library(httr)
library(httr)
library(xml2)